module.exports = {
  title: "Regenerative Farming and Bitcoin: A Better World Together",
  description:
    "A blog that captures AI-shaped ideas about the symbiosis between Regenerative Farming and Bitcoin, and how they can work together to make the world a better place for both humans and nature.",
  favicon:
    "https://void.cat/d/X43pvTionbCnJiSnXKHJTD.webp",
  logo: "https://void.cat/d/X43pvTionbCnJiSnXKHJTD.webp",
  npub: "npub1kmv8enh3jmrhf57gpe9n3z4npm8k03rsujrfgp7jc6x3tw8eegls9vegks",
  themes: [
    "light",
    "dark",
    "cupcake",
    "bumblebee",
    "emerald",
    "corporate",
    "synthwave",
    "retro",
    "cyberpunk",
    "valentine",
    "halloween",
    "garden",
    "forest",
    "aqua",
    "lofi",
    "pastel",
    "fantasy",
    "wireframe",
    "black",
    "luxury",
    "dracula",
    "cmyk",
    "autumn",
    "business",
    "acid",
    "lemonade",
    "night",
    "coffee",
    "winter",
  ],
  customThemes: [
    {
      custom: {
        primary: "#ef7951",
        secondary: "#ea0eb3",
        accent: "#9d66d1",
        neutral: "#1D252B",
        "base-100": "#403B59",
        info: "#A0BEE4",
        success: "#12825D",
        warning: "#C87114",
        error: "#E9445F",
      },
    },
  ],
  relays: [
    "wss://relay.snort.social",
    "wss://nostr-pub.wellorder.net",
    "wss://relay.damus.io",
    // "wss://nos.lol",
    // "wss://nostr.wine",
    // "wss://nostr.nostrelay.org",
    // "wss://relay.nostr.ch",
    // "wss://nostr.bitcoiner.social",
    // "wss://nostr.onsats.org",
    // "wss://nostr-relay.wlvs.space",
    // "wss://nostr.zebedee.cloud",
    // "wss://relay.nostr.info",
  ],
};
